version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: datalake_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root442002
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio-setup:
    image: minio/mc:latest
    container_name: datalake_minio_setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 root root442002 &&
      mc mb -p local/bronze  || true &&
      mc mb -p local/silver  || true &&
      mc mb -p local/gold    || true &&
      mc mb -p local/logs    || true &&
      echo 'Buckets created (or already exist)';
      "

volumes:
  minio_data: